Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MvcProje.Models.Entity;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MvcProje.Controllers
{
    public class UrunlerController : Controller
    {
        // GET: Urunler
        MvcDbStokEntities db = new MvcDbStokEntities();
        public ActionResult Index(int sayfa=1)
        {
            var urunler = db.TBLURUNLER.ToList();
            //var urunler = db.TBLURUNLER.ToList().ToPagedList(sayfa, 6);
            return View(urunler);
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList() select new SelectListItem { Text = i.KATEGORIAD, Value = i.KATEGORIID.ToString() }).ToList();
            ViewBag.ktg = degerler;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(TBLURUNLER parametre)
        {
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == parametre.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            parametre.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(parametre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var UrunSil = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(UrunSil);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGuncelle(int id)
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList() select new SelectListItem { Text = i.KATEGORIAD, Value = i.KATEGORIID.ToString() }).ToList();
            ViewBag.ktg = degerler;
            var urun = db.TBLURUNLER.Find(id);
            return View("UrunGuncelle", urun);
        }

        public ActionResult Guncelle(TBLURUNLER parametre)
        {
            var urun = db.TBLURUNLER.Find(parametre.URUNID);
            urun.URUNAD = parametre.URUNAD;
            urun.MARKA = parametre.MARKA;
            //urun.URUNKATEGORI = parametre.URUNKATEGORI;
            var ktg = db.TBLKATEGORILER.Where(m => m.KATEGORIID == parametre.TBLKATEGORILER.KATEGORIID).FirstOrDefault();
            urun.URUNKATEGORI = ktg.KATEGORIID;
            urun.FIYAT = parametre.FIYAT;
            urun.STOK = parametre.STOK;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Urunler/Index.cshtml
@using MvcProje.Models.Entity
@model List<TBLURUNLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}


<div">
    <table id="urunlertablo" class="table table-bordered">
        <thead>
            <tr>
                <th>Ürün ID</th>
                <th>Ürün AD</th>
                <th>Ürün Marka</th>
                <th>Ürün Kategori</th>
                <th>Ürün Fiyat</th>
                <th>Ürün Stok</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var urunler in Model)
            {

                <tr>
                    <td>@urunler.URUNID</td>
                    <td>@urunler.URUNAD</td>
                    <td>@urunler.MARKA</td>
                    <td>@urunler.TBLKATEGORILER.KATEGORIAD</td>
                    <td>@urunler.FIYAT</td>
                    <td>@urunler.STOK</td>
                    @*<td><a href="/Urunler/Sil/@urunler.URUNID" class="btn btn-danger">Sil</a></td>*@
                    <td>@Html.ActionLink("Ürün Sil", "Sil", new { id = urunler.URUNID }, new { @class = "btn btn-danger", onclick = "return confirm('Emin misin?')" })</td>
                    <td><a href="/Urunler/UrunGuncelle/@urunler.URUNID" class="btn btn-primary">Güncelle</a></td>

                </tr>

            }
        </tbody>
    </table>

    <a href="/Urunler/YeniUrun/" class="btn btn-success">Yeni Ürün Ekle</a>
    </div>

    <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js">
    </script>
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet" />

    <script>
        $('#urunlertablo').DataTable();
    </script>

Views/Urunler/UrunGuncelle.cshtml
@model MvcProje.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Ürün Güncelle</h2>



@using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
    {
    <div class="form-group">
        @Html.LabelFor(m => m.URUNID)
        @Html.TextBoxFor(m => m.URUNID, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNAD)
        @Html.TextBoxFor(m => m.URUNAD, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.MARKA)
        @Html.TextBoxFor(m => m.MARKA, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.URUNKATEGORI)
        @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.ktg, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.FIYAT)
        @Html.TextBoxFor(m => m.FIYAT, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.STOK)
        @Html.TextBoxFor(m => m.STOK, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
    }

Views/Urunler/YeniUrun.cshtml
@model MvcProje.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div>
    <form class="form-group" method="post">
        <div>
            <label>Ürün Ad:</label>
            <input type="text" class="form-control" name="UrunAd" required="" maxlength="50" placeholder="Ürün Adı:"/>
        </div>
        <div>
            <label>Marka:</label>
            <input type="text" class="form-control" name="Marka" required="" maxlength="50"/>
        </div>
        <div>
            <label>Kategori:</label>
            @Html.DropDownListFor(m => m.TBLKATEGORILER.KATEGORIID, (List<SelectListItem>)ViewBag.ktg, new { @class = "form-control" })
        </div>
        <div>
            <label>Fiyat:</label>
            <input type="text" class="form-control" name="Fiyat" value="0" required="" />
        </div>
        <div>
            <label>Stok:</label>
            <input type="text" class="form-control" name="Stok" value="0"  required="" />
        </div>
        <div style="margin-top:15px">
            <button class="btn btn-success">Ürün Ekle</button>
        </div>
    </form>
</div>